apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: staging
    app.kubernetes.io/name: service-b
    app.kubernetes.io/version: 0.1.1-next.0
  name: staging-service-b
  namespace: staging-service-b
spec: {}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/instance: staging
    app.kubernetes.io/name: service-b
    app.kubernetes.io/version: 0.1.1-next.0
  name: service-b-docker-auth-secret
  namespace: staging-service-b
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: name:docker-auth
        version: latest
      secretKey: secret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway
  target:
    creationPolicy: Owner
    name: service-b-docker-auth
    template:
      data:
        .dockerconfigjson: "{{ .secret | toString }}"
      type: kubernetes.io/dockerconfigjson
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/instance: staging
    app.kubernetes.io/name: service-b
    app.kubernetes.io/version: 0.1.1-next.0
  name: service-b-config-files-secrets
  namespace: staging-service-b
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: name:staging-service-b
        property: ACCOUNT_API_KEY
        version: latest
      secretKey: ACCOUNT_API_KEY
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway
  target:
    creationPolicy: Owner
    name: service-b-config-files
    template:
      data:
        config.json: '{"logLevel":"info","app":{"baseUrl":"staging.service-b.row.ovh","server":{"host":"0.0.0.0","port":4000}},"services":{"account":{"baseUrl":"staging.service-b.row.ovh","apiKey":"{{ .ACCOUNT_API_KEY | toString }}"}}}'
        data.csv: |-
          a,123
          b,456
          c,789
      engineVersion: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: service-b-config-files
  labels:
    app.kubernetes.io/component: app-server
    app.kubernetes.io/instance: staging
    app.kubernetes.io/name: service-b
    app.kubernetes.io/version: 0.1.1-next.0
  name: service-b-app-server
  namespace: staging-service-b
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: service-b-app-server-c810e653
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app-server
        app.kubernetes.io/instance: staging
        app.kubernetes.io/name: service-b
        app.kubernetes.io/version: 0.1.1-next.0
        cdk8s.io/metadata.addr: service-b-app-server-c810e653
    spec:
      automountServiceAccountToken: false
      containers:
        - command:
            - node
            - /app/applications/service-b/dist/server.js
          env:
            - name: CONFIG_FILE_PATH
              value: /app/config.json
          image: ghcr.io/mxvincent/service-b:0.1.1-next.0
          imagePullPolicy: Always
          name: app-server
          ports:
            - containerPort: 4000
              name: http
          resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
          volumeMounts:
            - mountPath: /app/config.json
              name: secret-service-b-config-files
              subPath: config.json
            - mountPath: /app/data.csv
              name: secret-service-b-config-files
              subPath: data.csv
      dnsPolicy: ClusterFirst
      hostNetwork: false
      imagePullSecrets:
        - name: service-b-docker-auth
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: true
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
        - name: secret-service-b-config-files
          secret:
            secretName: service-b-config-files
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: app-server
    app.kubernetes.io/instance: staging
    app.kubernetes.io/name: service-b
    app.kubernetes.io/version: 0.1.1-next.0
  name: service-b-app-server
  namespace: staging-service-b
spec:
  externalIPs: []
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  selector:
    cdk8s.io/metadata.addr: service-b-app-server-c810e653
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: acme
    ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    app.kubernetes.io/component: app-server
    app.kubernetes.io/instance: staging
    app.kubernetes.io/name: service-b
    app.kubernetes.io/version: 0.1.1-next.0
  name: service-b-app-server
  namespace: staging-service-b
spec:
  rules:
    - host: staging.service-b.row.ovh
      http:
        paths:
          - backend:
              service:
                name: service-b-app-server
                port:
                  number: 4000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - staging.service-b.row.ovh
      secretName: service-b-app-server-cert
