name: 'setup-node'
description: 'Setup NodeJS'
inputs:
  github-token:
    description: Token used to access GitHub dependencies
    required: false
runs:
  using: composite
  steps:
    - name: 'Inject token into .npmrc'
      shell: bash
      run: ./.github/actions/setup-node/configure-npm.sh
      env:
        GITHUB_TOKEN: '${{ inputs.github-token }}'
    - name: 'Setup NodeJS'
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: 'Install pnpm'
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 8.2.0
    - name: 'Get pnpm store directory'
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - name: 'Setup pnpm cache'
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
    - name: 'Resolve dependencies'
      shell: bash
      run: pnpm recursive install --frozen-lockfile
      env:
        HUSKY: '0' # By default do not run HUSKY install
    - name: 'Configure turbo cache'
      uses: dtinth/setup-github-actions-caching-for-turbo@v1
