apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: development-service-a
spec:
  destination:
    namespace: development-service-a
    server: https://kubernetes.default.svc
  project: node-packages
  source:
    directory:
      include: service-a.yaml
      recurse: false
    path: kubernetes/manifests/development
    repoURL: https://github.com/mxvincent/node-packages.git
    targetRevision: deploy/development
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: development-service-b
spec:
  destination:
    namespace: development-service-b
    server: https://kubernetes.default.svc
  project: node-packages
  source:
    directory:
      include: service-b.yaml
      recurse: false
    path: kubernetes/manifests/development
    repoURL: https://github.com/mxvincent/node-packages.git
    targetRevision: deploy/development
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
