apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: development
    app.kubernetes.io/name: service-a
    app.kubernetes.io/version: 0.1.0
  name: development-service-a
  namespace: development-service-a
spec: {}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/instance: development
    app.kubernetes.io/name: service-a
    app.kubernetes.io/version: 0.1.0
  name: service-a-docker-auth-secret
  namespace: development-service-a
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: name:docker-auth
        version: latest
      secretKey: secret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway
  target:
    creationPolicy: Owner
    name: service-a-docker-auth
    template:
      data:
        .dockerconfigjson: "{{ .secret | toString }}"
      type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: development
    app.kubernetes.io/name: service-a
    app.kubernetes.io/version: 0.1.0
  name: service-a-config-files
  namespace: development-service-a
immutable: false
stringData:
  config.json: '{"logLevel":"info","app":{"baseUrl":"development.service-a.row.ovh","server":{"host":"0.0.0.0","port":4000}}}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: service-a-config-files
  labels:
    app.kubernetes.io/component: app-server
    app.kubernetes.io/instance: development
    app.kubernetes.io/name: service-a
    app.kubernetes.io/version: 0.1.0
  name: service-a-app-server
  namespace: development-service-a
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: service-a-app-server-c8d3e0da
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app-server
        app.kubernetes.io/instance: development
        app.kubernetes.io/name: service-a
        app.kubernetes.io/version: 0.1.0
        cdk8s.io/metadata.addr: service-a-app-server-c8d3e0da
    spec:
      automountServiceAccountToken: false
      containers:
        - command:
            - node
            - /app/applications/service-a/dist/server.js
          env:
            - name: CONFIG_FILE_PATH
              value: /app/config.json
          image: ghcr.io/mxvincent/service-a:0.1.0
          imagePullPolicy: Always
          name: app-server
          ports:
            - containerPort: 4000
              name: http
          resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
          volumeMounts:
            - mountPath: /app/config.json
              name: secret-service-a-config-files
              subPath: config.json
      dnsPolicy: ClusterFirst
      hostNetwork: false
      imagePullSecrets:
        - name: service-a-docker-auth
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: true
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
        - name: secret-service-a-config-files
          secret:
            secretName: service-a-config-files
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: app-server
    app.kubernetes.io/instance: development
    app.kubernetes.io/name: service-a
    app.kubernetes.io/version: 0.1.0
  name: service-a-app-server
  namespace: development-service-a
spec:
  externalIPs: []
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  selector:
    cdk8s.io/metadata.addr: service-a-app-server-c8d3e0da
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: acme
    ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    app.kubernetes.io/component: app-server
    app.kubernetes.io/instance: development
    app.kubernetes.io/name: service-a
    app.kubernetes.io/version: 0.1.0
  name: service-a-app-server
  namespace: development-service-a
spec:
  rules:
    - host: development.service-a.row.ovh
      http:
        paths:
          - backend:
              service:
                name: service-a-app-server
                port:
                  number: 4000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - development.service-a.row.ovh
      secretName: service-a-app-server-cert
