name: 'deploy'
on:
  workflow_call:
    inputs:
      release-upstream:
        description: Release upstream
        type: string
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Setup NodeJS'
        uses: ./.github/actions/setup-node
      - name: 'Configure git'
        run: |
          git config --global user.name "gha-bot"
          git config --global user.email "bot@lab.ovh"
      - name: 'Update tag deploy/development'
        if: ${{ inputs.release-upstream == 'next' }}
        run: |
          git tag -f deploy/development
          git push -f origin deploy/development
      - name: 'Update tag deploy/staging'
        if: ${{ inputs.release-upstream == 'main' }}
        run: |
          git tag -f deploy/staging
          git push -f origin deploy/staging
